---
title: "Untitled"
author: "Ziyang Zhou"
date: "4/5/2017"
output:
  pdf_document: default
  html_document: default
---
```{r}
#load data
require(knitr)
setwd('~/Desktop/STAT_198/Data')
dfEW <- read.csv('extinct_in_wild_dates_and_location.csv')
dfEX <- read.csv('extinct_dates_and_location.csv')
load("PotentiallyExtinct.rda")
#function used to insert a row 
insertRow <- function(existingDF, newrow, r) {
  existingDF[seq(r+1,nrow(existingDF)+1),] <- existingDF[seq(r,nrow(existingDF)),]
  existingDF[r,] <- newrow
  existingDF
}
```

```{r}
#modify data set
dfEX <- na.omit(dfEX[ ,c(2,3,4,5,6,7,8,9,25,26)])
dfEW <- na.omit(dfEW[ ,c(2,3,4,5,6,7,8,9,25,26)])
dfEW<-rbind(dfEX,dfEW)

dfEW <- dfEW[dfEW$Phylum == "CHORDATA", ]
dfEW <- dfEW[,c(4,8,10)]
PE <- PE[,c(3,5,8)]
colnames(dfEW)[1:2] <- c("class","species")
EXverte <- rbind(dfEW, PE)

EXverte$Animal_Group <- rep(2,nrow(EXverte))
EXverte$Animal_Group[EXverte$class == "MAMMALIA"] <- 0 
EXverte$Animal_Group[EXverte$class == "MAMMALS"] <- 0 

EXverte$Animal_Group[EXverte$class == "AVES"] <- 1
EXverte$Animal_Group[EXverte$class == "BIRDS"] <- 1

EXbird <- EXverte[EXverte$Animal_Group == 1, ]
EXother <- EXverte[EXverte$Animal_Group == 2, ]
EXmammal <- EXverte[EXverte$Animal_Group == 0, ]

EXbird$last_seen <- as.numeric(EXbird$last_seen)
EXother$last_seen <- as.numeric(EXother$last_seen)
EXmammal$last_seen <- as.numeric(EXmammal$last_seen)
EXverte$last_seen <- as.numeric(EXverte$last_seen)
```


```{r}
#vertebrate group, seperate into 5 categories
EXverte.Groups <- aggregate(EXverte$species, 
                            by = list(cut(EXverte$last_seen,
                                          breaks = c(seq(1500,1900,100), 2010),
                                          include.lowest = T)), FUN = length)

colnames(EXverte.Groups) <- c("TimeInterval", "Num")
EXverte.Groups$CumSum <- cumsum(EXverte.Groups$Num)
EXverte.Groups$CumPer <- (EXverte.Groups$CumSum/43500)*100
EXverte.Groups$category <- rep("vertebrate", nrow(EXverte.Groups))

#brid group, seperate into 5 categories
EXbird.Groups <- aggregate(EXbird$species, by = list(cut(EXbird$last_seen,
                                                         breaks = c(seq(1500,1900,100), 2010),
                                                         include.lowest = T)), FUN = length)
colnames(EXbird.Groups) <- c("TimeInterval", "Num")
EXbird.Groups$CumSum <- cumsum(EXbird.Groups$Num)
EXbird.Groups$CumPer <- (EXbird.Groups$CumSum/11121)*100
EXbird.Groups$category <- rep("bird", nrow(EXbird.Groups))

#other group, seperate into 5 categories
EXother.Groups <- aggregate(EXother$species, by = list(cut(EXother$last_seen,
                                                           breaks = c(seq(1500,1900,100), 2010),
                                                           include.lowest = T)), FUN = length)
colnames(EXother.Groups) <- c("TimeInterval", "Num")
EXother.Groups$CumSum <- cumsum(EXother.Groups$Num)
EXother.Groups$CumPer <- (EXother.Groups$CumSum/26812)*100
row2 <- c("1600-1700", 0, 0, 0)
EXother.Groups <- insertRow(EXother.Groups, row2,2)
EXother.Groups$category <- rep("other", nrow(EXother.Groups))

#mammal group, seperate into 5 categories
EXmammal.Groups <- aggregate(EXmammal$species, by = list(cut(EXmammal$last_seen,
                                                           breaks = c(seq(1500,1900,100), 2010),
                                                           include.lowest = T)), FUN = length)
colnames(EXmammal.Groups) <- c("TimeInterval", "Num")
EXmammal.Groups$CumSum <- cumsum(EXmammal.Groups$Num)
EXmammal.Groups$CumPer <- (EXmammal.Groups$CumSum/5567)*100
EXmammal.Groups$category <- rep("mammal", nrow(EXmammal.Groups))

xx <- rep(0,5)
x <- seq(8.7, by = 8.7, length.out = 5)
Num <- rep(8.7, 5)
perx <- (x/43500)*100
cate <- rep("Background", 5)
EXbackRate <- data.frame(xx,Num, x,perx, cate)
colnames(EXbackRate) <- c("TimeInterval","Num","CumSum","CumPer","category")

EXtot <- rbind(EXverte.Groups, EXbird.Groups)
EXtot <- rbind(EXtot, EXother.Groups)
EXtot <- rbind(EXtot, EXmammal.Groups)
#EXtot <- EXtot[, c(1,4,5)]
EXtot <- rbind(EXtot, EXbackRate)
EXtot[,1] <- rep(c("1500~1600",
                  "1600~1700",
                  "1700~1800",
                  "1800~1900",
                  "1900~2010"), 5)

EXtot$CumSum <- as.numeric(EXtot$CumSum)
EXtot$Num <- as.numeric(EXtot$Num)
EXtot$CumPer <- as.numeric(EXtot$CumPer)
EXtot$category <- as.factor(EXtot$category)


save(EXtot, file = "conservative.rda")
```

```{r}
#conservative
#since 1500
NumSince1500 <- c(nrow(EXverte),nrow(EXmammal),nrow(EXbird),nrow(EXother))
NumSince1900 <- c(nrow(EXverte[EXverte$last_seen >= 1900, ]),
                  nrow(EXmammal[EXmammal$last_seen >= 1900, ]),
                  nrow(EXbird[EXbird$last_seen >= 1900, ]),
                  nrow(EXother[EXother$last_seen >= 1900, ]))
dfNum <- data.frame(NumSince1500,NumSince1900)
rownames(dfNum) <- c("Vertebrate", "Mammal", "Birds", "Others")


```


```{r}
#table of counts
kable(dfNum, row.names = T, align = "c", caption = "Conservative")
```

