---
title: "Untitled"
author: "Ziyang Zhou"
date: "4/23/2017"
output: html_document
---

```{r}
Dis = F
```


```{r, echo = F}
#package needed
require(ggplot2)
library(plyr)
require(reshape2)
library(knitr)
```


```{r, echo = Dis}
#load data
setwd('~/Desktop/STAT198/Data')
dfExtinct <- read.csv('extinct_dates_and_location.csv')
load("highlyconservative.rda")
load("conservative.rda")
HighConServative <- EXtt
ConServative <- EXtot
```

```{r, echo = Dis}
#Function used (from other sourses)
#function used to insert a row 
insertRow <- function(existingDF, newrow, r) {
  existingDF[seq(r+1,nrow(existingDF)+1),] <- existingDF[seq(r,nrow(existingDF)),]
  existingDF[r,] <- newrow
  existingDF
}

#multiplot
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


```{r, echo = Dis}
dfExtinct <- na.omit(dfExtinct[,c(2,3,4,5,6,7,8,9,25,26)])
#dfExtinct$category <- rep('EX', nrow(dfExtinct))

# following is the bar plot which only include the counts for Extinct species
ggplot(dfExtinct[dfExtinct$Phylum == "CHORDATA",], aes(last_seen)) +
  geom_histogram(binwidth = 25, alpha = 0.2,color = "black", boundary= 0 ) +
  scale_y_continuous(breaks = seq(0,40,10)) + 
  xlab("The year when the animials was last seen") +
  ggtitle("Extinct Vertebrates Counts Since 1500") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.title = element_text(size = rel(1.2)),
        axis.text.y = element_text(size = rel(1.2)),
        axis.text.x = element_text(size = rel(1.2)))

#ggsave("Counts.png", dpi = 400)#, width = 5, height = 5, units = "cm")

```


```{r, echo = Dis}
#Highly conservative
ggplot(HighConServative, aes(x = TimeInterval,y = CumPer, group = category)) +
  geom_line(aes(colour = category), size = 1.2) + 
  labs(x = "Time Interval", 
       y = "Cumulative extinctions as % of IUCN-evaluated species", 
       title = "Cumulative Extinction Rate (Highly Conservative)",
       color = "Animal Category") +
  scale_color_discrete(label = c("Background","Birds", "Mammal","Others","Vertebrates")) + 
  scale_y_continuous(breaks = seq(0,1.60,0.2), limits = c(0, 1.6)) + 
  scale_color_manual(values=c("grey50","tomato4", "blue4", "khaki3", "green4")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = rel(1.2)),
        axis.text.y = element_text(size = rel(1.2)),
        axis.text.x = element_text(size = rel(1.2)),
        legend.position = c(0.15,0.75),
        legend.text = element_text(size = rel(1.2)),
        legend.title = element_text(size = rel(1.2)),
        legend.direction = "vertical", 
        legend.spacing = unit(8,"mm"),
        legend.key.size = unit(10,"mm"),
        legend.background = element_rect(colour = "black"))+
        theme(plot.title = element_text(hjust = 0.5))


#ggsave("HighCon.png", scale = 1.2, dpi = 400)

#conservartive

ggplot(ConServative, aes(x = TimeInterval,y = CumPer, group = category)) +
  geom_line(aes(colour = category), size = 1.2) + 
  labs(x = "Time Interval", 
       y = "Cumulative extinctions as % of IUCN-evaluated species", 
       title = "Cumulative Extinction Rate (Conservative)",
       color = "Animal Category") +
  scale_color_discrete(label = c("Background","Birds", "Mammal","Others","Vertebrates")) + scale_y_continuous(breaks = seq(0,1.60,0.2), limits = c(0, 1.6)) + 
  scale_color_manual(values=c("grey50","tomato4", "blue4", "khaki3", "green4")) + 
  theme_bw() + 
  theme(plot.title = element_text(size = rel(1.2)),
        axis.text.y = element_text(size = rel(1.2)),
        axis.text.x = element_text(size = rel(1.2)),
        legend.position = c(0.15,0.75),
        legend.text = element_text(size = rel(1.2)),
        legend.title = element_text(size = rel(1.2)),
        legend.direction = "vertical", 
        legend.spacing = unit(8,"mm"),
        legend.key.size = unit(10,"mm"),
        legend.background = element_rect(colour = "black"))+
        theme(plot.title = element_text(hjust = 0.5))



#ggsave("Con.png", scale = 1.2, dpi = 400)

```

```{r}
#Poisson model
#birds 11121 mammals 5567 other 26812 total 43500 
#birds - 11121/43500 ~ 2.2
ggplot(HighConServative[HighConServative$category == "bird",]) + 
  geom_point(aes(x = TimeInterval, y = Num), size = 5, color = "tomato2") +
  geom_hline(yintercept = 2.2, size = 1, linetype = "dashed") + 
  geom_vline(xintercept = 3.5, size = 1, color = "grey") + 
  geom_line(aes(x = TimeInterval, y = Num, group = 1), linetype = "dotted", color = "grey50", size = 1)+
  labs(y = "Number of Extinctions") +
  annotate("text", x = 5, y = 5, label = "Poisson(2.2)", size = 5) +
  annotate("text", x = 3.5, y = 33, label = "Industralization", size = 5) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50")) +
   theme(plot.title = element_text(size = rel(1.5)),
        axis.text.y = element_text(size = rel(1.5)),
        axis.text.x = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(1.5)),
        panel.border = element_rect(colour = "black", fill=NA, size=1))

ggsave("PosBirds.png", scale = 1.2, dpi = 400, width = 5.43, height = 5.43, units = "in")

#mammals - 5567/43500 ~ 1.1
ggplot(HighConServative[HighConServative$category == "mammal",]) + 
  geom_point(aes(x = TimeInterval, y = Num), size = 5, color = "blue") +
  geom_hline(yintercept = 5.4, size = 1, linetype = "dashed") + 
  geom_vline(xintercept = 3.5, size = 1, color = "grey") + 
  geom_line(aes(x = TimeInterval, y = Num, group = 1), linetype = "dotted", color = "grey50", size = 1)+
  labs(y = "Number of Extinctions") +
  annotate("text", x = 5, y = 4, label = "Poisson(1.1)",size = 5) +
  annotate("text", x = 3.5, y = 20, label = "Industralization", size = 5) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50")) +
   theme(plot.title = element_text(size = rel(1.5)),
        axis.text.y = element_text(size = rel(1.5)),
        axis.text.x = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(1.5)),
        panel.border = element_rect(colour = "black", fill=NA, size=1))
ggsave("PosMammals.png", scale = 1.2, dpi = 400, width = 5.43, height = 5.43, units = "in")

#others - 26812/43500 ~ 5.4
ggplot(HighConServative[HighConServative$category == "other",]) + 
  geom_point(aes(x = TimeInterval, y = Num), size = 5, color = "khaki3") +
  geom_hline(yintercept = 5.4, size = 1, linetype = "dashed") + 
  geom_vline(xintercept = 3.5, size = 1, color = "grey") + 
  geom_line(aes(x = TimeInterval, y = Num, group = 1), linetype = "dotted", color = "grey50", size = 1)+
  labs(y = "Number of Extinctions") +
  annotate("text", x = 5, y = 8, label = "Poisson(5.4)",size =5) +
  annotate("text", x = 3.5, y = 30, label = "Industralization", size = 5) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
  theme(plot.title = element_text(size = rel(1.5)),
        axis.text.y = element_text(size = rel(1.5)),
        axis.text.x = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(1.5)),
        panel.border = element_rect(colour = "black", fill=NA, size=1))

ggsave("PosOther.png", scale = 1.2, dpi = 400, width = 5.43, height = 5.43, units = "in")

#vertebrates - 8.7
ggplot(HighConServative[HighConServative$category == "vertebrate",]) + 
  geom_point(aes(x = TimeInterval, y = Num), size = 5, color = "green4") +
  geom_hline(yintercept = 5.4, size = 1, linetype = "dashed") + 
  geom_vline(xintercept = 3.5, size = 1, color = "grey") + 
  geom_line(aes(x = TimeInterval, y = Num, group = 1), linetype = "dotted", color = "grey50", size = 1)+
  labs(y = "Number of Extinctions") +
  annotate("text", x = 5, y = 20, label = "Poisson(8.7)", size =5) +
  annotate("text", x = 3.5, y = 100, label = "Industralization", size = 5) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50")) +
  theme(plot.title = element_text(size = rel(1.5)),
        axis.text.y = element_text(size = rel(1.5)),
        axis.text.x = element_text(size = rel(1.5)),
        axis.title = element_text(size = rel(1.5)),
        panel.border = element_rect(colour = "black", fill=NA, size=1))

ggsave("PosVerte.png", scale = 1.2, dpi = 400)
```





